version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ourbackend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: ourfrontend
    ports:
      - "80:80"
    depends_on:
      - backend

  sqliteweb:
    image: coleifer/sqlite-web
    container_name: sqliteweb
    ports:
      - "8080:8080"
    volumes:
      - ./backend/database.db:/data/database.db
    command: ["sqlite_web", "/data/database.db", "--host", "0.0.0.0"]