version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: bimg
    ports:
    - "5000:5000"
    volumes:
      - ./backend/app
    container_name: cbend
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: fimg
    ports:
      - "80:80"
    container_name: cfend
    depends_on:
      - backend

  sqliteweb:
    image: coleifer/sqlite-web
    container_name: sqliteweb
    ports:
      - "8080:8080"
    volumes:
      - ./backend/database.db:/data/database.db
    command: ["sqlite_web", "/data/database.db", "--host", "0.0.0.0"]